/**
 * This class is generated by jOOQ
 */
package com.app.camel.model;


import com.app.camel.model.tables.Customer;
import com.app.camel.model.tables.CustomerProjects;
import com.app.camel.model.tables.Project;
import com.app.camel.model.tables.SchemaVersion;
import com.app.camel.model.tables.User;
import com.app.camel.model.tables.UserProjects;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in library
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>library.customer</code>.
     */
    public static final Customer CUSTOMER = com.app.camel.model.tables.Customer.CUSTOMER;

    /**
     * The table <code>library.customer_projects</code>.
     */
    public static final CustomerProjects CUSTOMER_PROJECTS = com.app.camel.model.tables.CustomerProjects.CUSTOMER_PROJECTS;

    /**
     * The table <code>library.project</code>.
     */
    public static final Project PROJECT = com.app.camel.model.tables.Project.PROJECT;

    /**
     * The table <code>library.schema_version</code>.
     */
    public static final SchemaVersion SCHEMA_VERSION = com.app.camel.model.tables.SchemaVersion.SCHEMA_VERSION;

    /**
     * The table <code>library.user</code>.
     */
    public static final User USER = com.app.camel.model.tables.User.USER;

    /**
     * The table <code>library.user_projects</code>.
     */
    public static final UserProjects USER_PROJECTS = com.app.camel.model.tables.UserProjects.USER_PROJECTS;
}
