/**
 * This class is generated by jOOQ
 */
package com.app.camel.model.tables;


import com.app.camel.model.Keys;
import com.app.camel.model.Library;
import com.app.camel.model.tables.records.PositionRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Position extends TableImpl<PositionRecord> {

    private static final long serialVersionUID = 2046626427;

    /**
     * The reference instance of <code>library.position</code>
     */
    public static final Position POSITION = new Position();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PositionRecord> getRecordType() {
        return PositionRecord.class;
    }

    /**
     * The column <code>library.position.id</code>.
     */
    public final TableField<PositionRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>library.position.position</code>.
     */
    public final TableField<PositionRecord, String> POSITION_ = createField("position", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * Create a <code>library.position</code> table reference
     */
    public Position() {
        this("position", null);
    }

    /**
     * Create an aliased <code>library.position</code> table reference
     */
    public Position(String alias) {
        this(alias, POSITION);
    }

    private Position(String alias, Table<PositionRecord> aliased) {
        this(alias, aliased, null);
    }

    private Position(String alias, Table<PositionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Library.LIBRARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PositionRecord, Integer> getIdentity() {
        return Keys.IDENTITY_POSITION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PositionRecord> getPrimaryKey() {
        return Keys.KEY_POSITION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PositionRecord>> getKeys() {
        return Arrays.<UniqueKey<PositionRecord>>asList(Keys.KEY_POSITION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Position as(String alias) {
        return new Position(alias, this);
    }

    /**
     * Rename this table
     */
    public Position rename(String name) {
        return new Position(name, null);
    }
}
