/**
 * This class is generated by jOOQ
 */
package com.app.camel.model.tables.records;


import com.app.camel.model.tables.Salary;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SalaryRecord extends UpdatableRecordImpl<SalaryRecord> implements Record7<Integer, Integer, Integer, Integer, Integer, Date, Date> {

    private static final long serialVersionUID = 1708430175;

    /**
     * Setter for <code>library.salary.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>library.salary.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>library.salary.Users_id</code>.
     */
    public void setUsersId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>library.salary.Users_id</code>.
     */
    public Integer getUsersId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>library.salary.Positions_id</code>.
     */
    public void setPositionsId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>library.salary.Positions_id</code>.
     */
    public Integer getPositionsId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>library.salary.monthly</code>.
     */
    public void setMonthly(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>library.salary.monthly</code>.
     */
    public Integer getMonthly() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>library.salary.per_hour</code>.
     */
    public void setPerHour(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>library.salary.per_hour</code>.
     */
    public Integer getPerHour() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>library.salary.date_from</code>.
     */
    public void setDateFrom(Date value) {
        set(5, value);
    }

    /**
     * Getter for <code>library.salary.date_from</code>.
     */
    public Date getDateFrom() {
        return (Date) get(5);
    }

    /**
     * Setter for <code>library.salary.date_to</code>.
     */
    public void setDateTo(Date value) {
        set(6, value);
    }

    /**
     * Getter for <code>library.salary.date_to</code>.
     */
    public Date getDateTo() {
        return (Date) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, Integer, Integer, Date, Date> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, Integer, Integer, Date, Date> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Salary.SALARY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Salary.SALARY.USERS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Salary.SALARY.POSITIONS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Salary.SALARY.MONTHLY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Salary.SALARY.PER_HOUR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field6() {
        return Salary.SALARY.DATE_FROM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field7() {
        return Salary.SALARY.DATE_TO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUsersId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getPositionsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getMonthly();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getPerHour();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value6() {
        return getDateFrom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value7() {
        return getDateTo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SalaryRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SalaryRecord value2(Integer value) {
        setUsersId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SalaryRecord value3(Integer value) {
        setPositionsId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SalaryRecord value4(Integer value) {
        setMonthly(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SalaryRecord value5(Integer value) {
        setPerHour(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SalaryRecord value6(Date value) {
        setDateFrom(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SalaryRecord value7(Date value) {
        setDateTo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SalaryRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, Date value6, Date value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SalaryRecord
     */
    public SalaryRecord() {
        super(Salary.SALARY);
    }

    /**
     * Create a detached, initialised SalaryRecord
     */
    public SalaryRecord(Integer id, Integer usersId, Integer positionsId, Integer monthly, Integer perHour, Date dateFrom, Date dateTo) {
        super(Salary.SALARY);

        set(0, id);
        set(1, usersId);
        set(2, positionsId);
        set(3, monthly);
        set(4, perHour);
        set(5, dateFrom);
        set(6, dateTo);
    }
}
