/**
 * This class is generated by jOOQ
 */
package com.app.camel.model.tables.records;


import com.app.camel.model.tables.UserSkill;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserSkillRecord extends UpdatableRecordImpl<UserSkillRecord> implements Record4<Integer, Integer, Integer, byte[]> {

    private static final long serialVersionUID = 1840923684;

    /**
     * Setter for <code>library.user_skill.skill_id</code>.
     */
    public void setSkillId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>library.user_skill.skill_id</code>.
     */
    public Integer getSkillId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>library.user_skill.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>library.user_skill.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>library.user_skill.level</code>.
     */
    public void setLevel(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>library.user_skill.level</code>.
     */
    public Integer getLevel() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>library.user_skill.note</code>.
     */
    public void setNote(byte[] value) {
        set(3, value);
    }

    /**
     * Getter for <code>library.user_skill.note</code>.
     */
    public byte[] getNote() {
        return (byte[]) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, byte[]> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, byte[]> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserSkill.USER_SKILL.SKILL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return UserSkill.USER_SKILL.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return UserSkill.USER_SKILL.LEVEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field4() {
        return UserSkill.USER_SKILL.NOTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getSkillId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value4() {
        return getNote();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSkillRecord value1(Integer value) {
        setSkillId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSkillRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSkillRecord value3(Integer value) {
        setLevel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSkillRecord value4(byte[] value) {
        setNote(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSkillRecord values(Integer value1, Integer value2, Integer value3, byte[] value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserSkillRecord
     */
    public UserSkillRecord() {
        super(UserSkill.USER_SKILL);
    }

    /**
     * Create a detached, initialised UserSkillRecord
     */
    public UserSkillRecord(Integer skillId, Integer userId, Integer level, byte[] note) {
        super(UserSkill.USER_SKILL);

        set(0, skillId);
        set(1, userId);
        set(2, level);
        set(3, note);
    }
}
