/**
 * This class is generated by jOOQ
 */
package com.app.camel.model.tables.records;


import com.app.camel.model.tables.UserProjects;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserProjectsRecord extends UpdatableRecordImpl<UserProjectsRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = -727336975;

    /**
     * Setter for <code>library.user_projects.Users_id</code>.
     */
    public void setUsersId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>library.user_projects.Users_id</code>.
     */
    public Integer getUsersId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>library.user_projects.Projects_id</code>.
     */
    public void setProjectsId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>library.user_projects.Projects_id</code>.
     */
    public Integer getProjectsId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserProjects.USER_PROJECTS.USERS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return UserProjects.USER_PROJECTS.PROJECTS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getUsersId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getProjectsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserProjectsRecord value1(Integer value) {
        setUsersId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserProjectsRecord value2(Integer value) {
        setProjectsId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserProjectsRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserProjectsRecord
     */
    public UserProjectsRecord() {
        super(UserProjects.USER_PROJECTS);
    }

    /**
     * Create a detached, initialised UserProjectsRecord
     */
    public UserProjectsRecord(Integer usersId, Integer projectsId) {
        super(UserProjects.USER_PROJECTS);

        set(0, usersId);
        set(1, projectsId);
    }
}
